version: '3.6'
services:
  mymongodb:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
      - kafka-network
  
  iot-consumer:
    build: 
      context: ./
      dockerfile: docker/consumer.Dockerfile
    container_name: iot-consumer
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=iot
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8081:8081
    depends_on:
      - mymongodb
    networks:
      - app-network
      - kafka-network
  iot-api:
    build: 
      context: ./
      dockerfile: docker/api.Dockerfile
    container_name: iot-api
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=iot
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8082:8082
    depends_on:
      - mymongodb
    networks:
      - app-network
      - kafka-network
  iot-model:
    build: 
      context: ./
      dockerfile: docker/model.Dockerfile
    container_name: iot-model
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8086:8086
    networks:
      - app-network
      - kafka-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network
  kafka_0:
    image: confluentinc/cp-kafka:7.0.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_CREATE_TOPICS: "iot-data:3:3"
    networks:
      - kafka-network
  kafka_1:
    image: confluentinc/cp-kafka:7.0.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_1:29093,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENERS: PLAINTEXT://:29093,PLAINTEXT_HOST://:9094
      KAFKA_CREATE_TOPICS: "iot-data:3:3"
    networks:
      - kafka-network
  kafka_2:
    image: confluentinc/cp-kafka:7.0.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_2:29094,PLAINTEXT_HOST://localhost:9095
      KAFKA_LISTENERS: PLAINTEXT://:29094,PLAINTEXT_HOST://:9095
      KAFKA_CREATE_TOPICS: "iot-data:3:3"
    networks:
      - kafka-network
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka_0:29092,kafka_1:29093, kafka_2:29094"
    depends_on:
      - "kafka_0"
      - "kafka_1"
      - "kafka_2"
    networks:
      - kafka-network
  producer-api:
    build: 
      context: ./
      dockerfile: docker/producer.Dockerfile
    container_name: iot-producer  
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  
    networks:
      - app-network
      - kafka-network
    depends_on:
      - kafka_0      
    
networks:
  kafka-network:
    driver: bridge
  app-network:
    driver: bridge  
